//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frankfurter.API.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Currencies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Currencies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frankfurter.API.Client.Resources.Currencies", typeof(Currencies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUD.
        /// </summary>
        internal static string AustralianDollar {
            get {
                return ResourceManager.GetString("AustralianDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRL.
        /// </summary>
        internal static string BrazilianReal {
            get {
                return ResourceManager.GetString("BrazilianReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        internal static string BritishPound {
            get {
                return ResourceManager.GetString("BritishPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGN.
        /// </summary>
        internal static string BulgarianLev {
            get {
                return ResourceManager.GetString("BulgarianLev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        internal static string CanadianDollar {
            get {
                return ResourceManager.GetString("CanadianDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY.
        /// </summary>
        internal static string ChineseRenminbiYuan {
            get {
                return ResourceManager.GetString("ChineseRenminbiYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZK.
        /// </summary>
        internal static string CzechKoruna {
            get {
                return ResourceManager.GetString("CzechKoruna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKK.
        /// </summary>
        internal static string Danish_Krone {
            get {
                return ResourceManager.GetString("Danish Krone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKD.
        /// </summary>
        internal static string HongKongDollar {
            get {
                return ResourceManager.GetString("HongKongDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUF.
        /// </summary>
        internal static string HungarianForint {
            get {
                return ResourceManager.GetString("HungarianForint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISK.
        /// </summary>
        internal static string IcelandicKrona {
            get {
                return ResourceManager.GetString("IcelandicKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INR.
        /// </summary>
        internal static string IndianRupee {
            get {
                return ResourceManager.GetString("IndianRupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR.
        /// </summary>
        internal static string IndonesianRupiah {
            get {
                return ResourceManager.GetString("IndonesianRupiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS.
        /// </summary>
        internal static string IsraeliNewSheqel {
            get {
                return ResourceManager.GetString("IsraeliNewSheqel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY.
        /// </summary>
        internal static string JapaneseYen {
            get {
                return ResourceManager.GetString("JapaneseYen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYR.
        /// </summary>
        internal static string MalaysianRinggit {
            get {
                return ResourceManager.GetString("MalaysianRinggit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MXN.
        /// </summary>
        internal static string MexicanPeso {
            get {
                return ResourceManager.GetString("MexicanPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZD.
        /// </summary>
        internal static string NewZealandDollar {
            get {
                return ResourceManager.GetString("NewZealandDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOK.
        /// </summary>
        internal static string NorwegianKrone {
            get {
                return ResourceManager.GetString("NorwegianKrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP.
        /// </summary>
        internal static string PhilippinePeso {
            get {
                return ResourceManager.GetString("PhilippinePeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLN.
        /// </summary>
        internal static string PolishZłoty {
            get {
                return ResourceManager.GetString("PolishZłoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RON.
        /// </summary>
        internal static string RomanianLeu {
            get {
                return ResourceManager.GetString("RomanianLeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGD.
        /// </summary>
        internal static string SingaporeDollar {
            get {
                return ResourceManager.GetString("SingaporeDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAR.
        /// </summary>
        internal static string SouthAfricanRand {
            get {
                return ResourceManager.GetString("SouthAfricanRand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRW.
        /// </summary>
        internal static string SouthKoreanWon {
            get {
                return ResourceManager.GetString("SouthKoreanWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEK.
        /// </summary>
        internal static string SwedishKrona {
            get {
                return ResourceManager.GetString("SwedishKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF.
        /// </summary>
        internal static string SwissFranc {
            get {
                return ResourceManager.GetString("SwissFranc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THB.
        /// </summary>
        internal static string ThaiBaht {
            get {
                return ResourceManager.GetString("ThaiBaht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY.
        /// </summary>
        internal static string TurkishLira {
            get {
                return ResourceManager.GetString("TurkishLira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string UnitedStatesDollar {
            get {
                return ResourceManager.GetString("UnitedStatesDollar", resourceCulture);
            }
        }
    }
}
